language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

sudo: required

# command to install dependencies
install: "pip install -r requirements.txt"

before_script: export PYTHONPATH=$PYTHONPATH:$(pwd)

# command to run tests
script:
  - python blockchain/tests/*.py
