language: python
python:
  - "2.7"

env:
  - PYTHONPATH=~/build/dragonchain/dragonchain

sudo: required

# command to install dependencies
install: "pip install -r requirements.txt"

# command to run tests
script:
  - python blockchain/tests/crypto_utest.py
